# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ytrss < Formula
  desc "A CLI tool to get RSS feeds for YouTube channels and playlists."
  homepage "https://github.com/lsherman98/yt-rss-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lsherman98/yt-rss-cli/releases/download/v1.0.0/yt-rss-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "849517e186cac37929c0b4b1ad646042ac7e17f9cb232858ea7d0f6e84986869"

      def install
        bin.install "ytrss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lsherman98/yt-rss-cli/releases/download/v1.0.0/yt-rss-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "94c8ba254bd650be4affbfe749a5d3e80edb2fa99e213280801c8260d5057c92"

      def install
        bin.install "ytrss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lsherman98/yt-rss-cli/releases/download/v1.0.0/yt-rss-cli_1.0.0_linux_amd64.tar.gz"
      sha256 "9d62a3581dbe254f530bd80fe1086ef953441ddfbcdd10de3fb7da425581bbc7"
      def install
        bin.install "ytrss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lsherman98/yt-rss-cli/releases/download/v1.0.0/yt-rss-cli_1.0.0_linux_arm64.tar.gz"
      sha256 "2b3ca83ca931db37d93c5567fcf770894ddb63c60397dbe8ffdf2cacd8f0b435"
      def install
        bin.install "ytrss"
      end
    end
  end
end
