# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ytrss < Formula
  desc "A CLI tool to get RSS feeds for YouTube channels and playlists."
  homepage "https://github.com/lsherman98/yt-rss-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lsherman98/yt-rss-cli/releases/download/v1.0.0/yt-rss-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "13e238896bf945b9d463c752a7aa79e268d2c26b501201ff00a473863b0a4502"

      def install
        bin.install "ytrss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lsherman98/yt-rss-cli/releases/download/v1.0.0/yt-rss-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "ef34c2bd4fef42d6f67d9c934e306684b02daf1a334a70005c0366b6a0e686d7"

      def install
        bin.install "ytrss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lsherman98/yt-rss-cli/releases/download/v1.0.0/yt-rss-cli_1.0.0_linux_amd64.tar.gz"
      sha256 "587e8d4b5cbb86a16c4d715bc478816e6e488afbcb431ee1054de96fb2300e26"
      def install
        bin.install "ytrss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lsherman98/yt-rss-cli/releases/download/v1.0.0/yt-rss-cli_1.0.0_linux_arm64.tar.gz"
      sha256 "b21a6a259d3fca3c41dece22027600ce0aa2c672563aacab9bf7fbe30f9d713e"
      def install
        bin.install "ytrss"
      end
    end
  end
end
