# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ytrss < Formula
  desc "A CLI tool to get RSS feeds for YouTube channels and playlists."
  homepage "https://github.com/lsherman98/yt-rss-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lsherman98/yt-rss-cli/releases/download/v1.0.0/yt-rss-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "e61529563c4cb6574b4548308d1ee24f03e07f640d2f9db069891c1a93ad57a4"

      def install
        bin.install "ytrss"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lsherman98/yt-rss-cli/releases/download/v1.0.0/yt-rss-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "b33936007075c8228d36f64ae14c735828d5eaacd85be48cc0138e17ceca3731"

      def install
        bin.install "ytrss"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lsherman98/yt-rss-cli/releases/download/v1.0.0/yt-rss-cli_1.0.0_linux_amd64.tar.gz"
      sha256 "298f18d72396e4196cc387698925716f39a74c1892e7fa475b2d1a029c2e2848"
      def install
        bin.install "ytrss"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lsherman98/yt-rss-cli/releases/download/v1.0.0/yt-rss-cli_1.0.0_linux_arm64.tar.gz"
      sha256 "d88e9affd8da713f7e7c641d30f3df0d5cd7bea970f5cd541865ef3026fe6874"
      def install
        bin.install "ytrss"
      end
    end
  end
end
